import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header/Header'
import styles from '../sass/Home.module.scss'
import ChooseContinentSection from './home-sections/choose-continent-section/chooseContinentSection'
import PlaneSection from './home-sections/plane-section/planeSection'
import TravelTypesSection from './home-sections/travel-types-section/travelTypesSection'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={styles.main}>
        <PlaneSection/>
        <TravelTypesSection/>
        <ChooseContinentSection/>
      </main>

    </div>
  )
}

export default Home
